language: java
jdk:
  - openjdk12
before_install:
  - wget https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar zxvf apache-maven-3.6.3-bin.tar.gz
  - export M2_HOME=$PWD/apache-maven-3.6.3
  - export PATH=$M2_HOME/bin:$PATH
script:
  - mvn clean install -Pdistribution,tomcat7 -DskipTests=true
branches:
  only:
    - main
cache:
  directories:
    - $HOME/.m2
