language: java
jdk:
  - openjdk8
before_install:
  - chmod +x ./travis/install.sh
  - ./travis/install.sh
script:
  - mvn clean install -Pdistribution,tomcat7 -DskipTests=true
after_success:
  - ./travis/deploy.sh
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.m2
