language: java
jdk:
  - openjdk8
before_install:
  - chmod +x ./travis/install.sh
  - ./travis/install.sh
script:
  - mvn clean install -Poperator -DskipTests
after_success:
  - ./travis/deploy.sh
branches:
  only:
    - main
cache:
  directories:
    - $HOME/.m2
